options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build -t us-central1-docker.pkg.dev/niveus-infra-gcp-training12/prathijna-imag/prathijna-docker:latest .
        docker push us-central1-docker.pkg.dev/niveus-infra-gcp-training12/prathijna-imag/prathijna-docker:latest
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth list
        gcloud config list
